<?php

namespace Tests\Feature\Admin;

use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class HomeController extends TestCase
{

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->seeding();
    }

    public function test_visit_home()
    {
        $response = $this->auth()->get(route('admin.index'));
        $response->assertSee(__('messages.welcome_to_the_admin_panel'));
    }

    public function test_visit_home_not_auth()
    {
        $response = $this->get(route('admin.index'));
        $response->assertRedirect(route('login'));
    }
}
