<?php

namespace Tests;

use App\Models\User;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->artisan('migrate');
        $this->artisan('db:seed');
    }

    protected function ajaxPost($uri, array $data = [])
    {
        return $this->post($uri, $data, array('HTTP_X-Requested-With' => 'XMLHttpRequest'));
    }


    protected function ajaxGet($uri, array $data = [])
    {
        return $this->get($uri, array('HTTP_X-Requested-With' => 'XMLHttpRequest'));
    }

    public function auth($role = User::ROLE_ADMIN)
    {
        $user = User::whereHas('roles', function ($query) use ($role) {
            $query->whereName($role);
        })->first();
        dd($user);
        return $this->actingAs($user);
    }

    public function seeding($classSeeder = null)
    {
        if (is_null($classSeeder)) {
            $this->artisan('db:seed');
        } else {
            $this->artisan('db:seed --class=' . $classSeeder);
        }
    }
}
